### ISSUE TITLE
項目数の上限はどのくらいなのでしょうか？

### ISSUE THREAD

**Issue by zanjibar** [nysol/mcmd#3]
項目数２万くらいのデータを扱いたいのですが、どこまで可能なのでしょうか？ @hamuro

**Comment by nainM** [comment]
項目数に制限はありませんが１行のデータ量に制限があります（1,024,000バイト）

**Comment by zanjibar** [comment]
ありがとうございます。項目数が多いDBのンチマークを行っています。対比するDBが存在しないので、こまっていたところです。
