### ISSUE TITLE
ubuntu 20.04LTS でコンパイル可能でしょうか？

### ISSUE THREAD

**Issue by zanjibar** [nysol/mcmd#4]
docker の jupyter/minimal-notebook:latest　にインストールしようとしたら、make install までいったのですが、

`(base) jovyan@71fab9bf4ea2:~/work$ mcut --help
mcut: error while loading shared libraries: libkgmod3.so.1: cannot open shared object file: No such file or directory
`
というエラーがでました。
Docker image はこれです。回避可能でしょうか？
https://hub.docker.com/r/jupyter/minimal-notebook

**Comment by zanjibar** [comment]
とりあえず、進歩しました。
/usr/local/lib を追加して、
 sudo ldconfig したら、mcut --help まで動きました。
`(base) jovyan@71fab9bf4ea2:~/work$ cat /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf
/usr/local/lib
`
warning はでまくっていたので、その後問題があるかもしれません。

**Comment by zanjibar** [comment]
動いたので、dockerhub にあげました。 zanjibar/minimal-notebook_nysol

**Comment by nainM** [comment]
error while loading shared libraries: libkgmod3.so.1: は共有ライブラリが見つからないという
エラーなので対応してもらった ldconfig でOKだと思います
warningは他のversionで出ているものだと思うのでおそらく問題ないと思います

**Comment by zanjibar** [comment]
ありがとうございます。まずは動くということですね。
