### ISSUE TITLE
-nfn 指定時に、最後の項目の指定を f=-1 のような形式で指定は可能でしょうか？

### ISSUE THREAD

**Issue by zanjibar** [nysol/mcmd#5]
python のスライスのときは、-1 とすると最後になります。同様のことを mcmdでできないでしょうか？

**Comment by h-maru** [comment]
可能です。
こちらをご参照ください。
[「3.6. 項目名ヘッダーなしでの利用」多様な項目番号の指定方法](https://www.nysol.jp/nysol_python/mcmd/field.html#id9)

**Comment by zanjibar** [comment]
ありがとうございます。大文字Lで指定するとできますね。非常に助かります。

**Comment by zanjibar** [comment]
解決したので閉じます。
