### ISSUE TITLE
-nfn での　mjoin の挙動について 

### ISSUE THREAD

**Issue by zanjibar** [nysol/mcmd#6]
10 ,11 がjoin しません。 項目をたてるとjoin　できます。-nfn オプションの問題な気がします。

tmp.dat
```
10
10
11
5
5
5
```
ref.dat
```
5,aaa
10,bbb
11,ccc
```
 mjoin  -nfn  k=0 i=tmp.dat m=ref.dat を実行
```
[centos@i5 work]$ mjoin  -nfn  k=0 i=tmp.dat m=ref.dat
5,aaa
5,aaa
5,aaa
#END# kgjoin -nfn i=tmp.dat k=0 m=ref.dat; IN=6 OUT=3; 2021/12/10 18:07:08
```

項目ありにすると

tmp.dat
```
seq
10
10
11
5
5
5
```

ref.dat
```
seq,text
5,aaa
10,bbb
11,ccc
```

mjoin    k=seq i=tmp.dat m=ref.dat
```
seq%0,text
10,bbb
10,bbb
11,ccc
5,aaa
5,aaa
5,aaa
#END# kgjoin i=tmp.dat k=seq m=ref.dat; IN=6 OUT=6; 2021/12/10 18:10:41
```

**Comment by h-maru** [comment]
nysol/mcmdでは出力ファイルの項目名にマークを付加してデータのソート状態を保持しています。ファイル結合などの処理では両方のファイルを同じルールでソートしてから処理する必要がありますが、mcmdでは項目名からソート状態を判断し、必要であれば処理内部で自動的にソートを実行してからメイン処理を行います。

nfnオプションでコマンドを実行する場合はソート状態を判断することができないため、内部処理での自動ソートを行わない仕様となっています。そのため、事前にmsortfなどを使用してソートしたファイルをインプットに用いる必要があります。また、mcmdの標準のソートルールは文字昇順ソートになります。

例示されているtmp.datファイルは結合キー項目で文字昇順になっていますが、ref.datは数値昇順ですので、結果としてref.datの最初のデータのみ結合されたことになっています。ref.datを文字昇順でソートしたファイルを結合すれば意図されている処理結果を得れます。

**Comment by zanjibar** [comment]
早速、ありがとうございます。項目名なし運用だと要注意ですね。ドキュメントにも書いてあるとたすかります。ほぼ、-nfn  での運用をする状況なので、他にも関連した問題ないかを注意したいところです。

**Comment by zanjibar** [comment]
tmp.dat ref.dat ともにソートしないといけないみたいですね。

**Comment by h-maru** [comment]
はい、そうなります。マッチングのロジックが動きますので、結合する両ファイルとマッチングロジックが採用しているソートのルールがすべて同じである必要があります。
インプットがヘッダー項目なしのファイルばかりを対象にする場合は、NYSOLでの処理の最初に項目名を付与して後続の処理を実行して一番最後にヘッダーを除いて出力するという方法をおすすめします。
ヘッダー項目がないファイルに項目名を付与するには
`mcut i=ref.dat -nfni f=0:col1,1:col2`
もしくは
`mcut i=ref.dat -nfni f=0-0L`
などとすればできます。

**Comment by zanjibar** [comment]
レス遅れてすみません。途中で必要なところだけ、項目名付与して、 %n のように運用するわけですね。

**Comment by zanjibar** [comment]
解決したんで、クローズします。
